version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 561880438739.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t test-doc-ecr:latest .
      - docker tag test-doc-ecr:latest 561880438739.dkr.ecr.us-east-1.amazonaws.com/test-doc-ecr:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 561880438739.dkr.ecr.us-east-1.amazonaws.com/test-doc-ecr:latest
